FROM elixir:1.17.0-otp-27-alpine AS build

RUN apk add --no-cache \
    build-base \
    git \
    inotify-tools

WORKDIR /app

COPY . .

COPY entrypoint.dev.sh /usr/local/bin/entrypoint.dev.sh

RUN chmod +x /usr/local/bin/entrypoint.dev.sh

EXPOSE 4000
    
CMD ["/usr/local/bin/entrypoint.dev.sh"]